name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Replace 'main' with the branch that triggers live deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Clear NPM Cache
      - name: Clear NPM Cache
        run: npm cache clean --force

      # Step 3: Install Dependencies using npm ci (install dependencies defined in package-lock.json)
      - name: Install Dependencies
        run: npm ci

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MODULE2424CICD }}
          channelId: live
          projectId: module2424cicd
